import { test, expect } from '@playwright/test'
import { lessons } from '../../src/data/lessons.js'

test('cards flip, rate, wrap around and keep ratings after reload', async ({ page }, info) => {
  await page.goto('/')
  await page.locator('#continue').click()
  await page.locator('#learn-cards').click()
  await expect(page.locator('#tab-cards')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#flashcard strong')).toHaveText('A a')
  await expect(page.locator('#rate-known')).toHaveCount(0)
  await page.locator('#previous-card').click()
  await expect(page.locator('.card-nav .meta')).toHaveText(`${lessons[0].cards.length} / ${lessons[0].cards.length}`)
  await page.locator('#next-card').click()
  await page.locator('#flashcard').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#flashcard')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.flip-hint')).toContainText('recto')
  await page.locator('#rate-known').click()
  await expect(page.locator('#flashcard')).toBeFocused()
  await expect(page.locator('#flashcard')).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.card-nav .meta')).toHaveText(`2 / ${lessons[0].cards.length}`)
  await expect(page.locator('.known-label')).toContainText('1 /')
  await page.reload()
  await page.locator('#continue').click()
  await expect(page.locator('#tab-cards')).toHaveAttribute('aria-pressed', 'true')
  await page.locator('#previous-card').click()
  await expect(page.locator('.activity > article > .meta').first()).toHaveText('Carte connue')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('cards.png'), fullPage: true })
})
