import { test, expect } from '@playwright/test'
import { lessons } from '../../src/data/lessons.js'
import { english } from '../../src/data/english.js'

test('French stays default; English preference and in-progress work survive toggling', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('html')).toHaveAttribute('lang', 'fr')
  await expect(page.locator('#english-toggle')).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.english-note')).toHaveCount(0)
  await page.locator('#english-toggle').click()
  await expect(page.locator('#english-toggle')).toBeFocused()
  await expect(page.locator('#english-toggle')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.teaching-section').first()).toContainText(english.alphabet.sections[0])
  await expect(page.locator('.teaching-section').first()).toContainText(lessons[0].sections[0][1])
  await page.locator('#mode-writing').click()
  await page.locator('#writing-answer').fill('Je suis Ada.')
  await page.locator('#english-toggle').click()
  await expect(page.locator('#writing-answer')).toHaveValue('Je suis Ada.')
  await expect(page.locator('.english-note')).toHaveCount(0)
  await page.locator('#english-toggle').click()
  await page.reload()
  await expect(page.locator('#english-toggle')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#writing-answer')).toHaveValue('Je suis Ada.')
  await page.locator('#english-toggle').click()
  await page.reload()
  await expect(page.locator('.english-note')).toHaveCount(0)
})

test('English instructions do not reveal answers and feedback works in quiz and daily review', async ({ page }) => {
  await page.goto('/')
  await page.locator('#english-toggle').click()
  await page.locator('#mode-exercises').click()
  await expect(page.locator('.exercise').first()).toContainText(english.alphabet.exercises[0])
  await expect(page.locator('#feedback-0')).toBeEmpty()
  await page.locator('#answer-0').fill('wrong')
  await page.locator('#check-0').click()
  await expect(page.locator('#feedback-0')).toContainText('Not quite.')
  await page.locator('#feedback-0 summary').click()
  await expect(page.locator('#feedback-0')).toContainText(english.alphabet.sections[0])
  await page.locator('#mode-quiz').click()
  await expect(page.locator('.quiz-panel')).toContainText(english.alphabet.questions[0])
  await expect(page.locator('.quiz-result')).toHaveCount(0)
  await expect(page.locator('.english-rules')).toHaveCount(0)
  await page.locator('.option').nth(1).click()
  await expect(page.locator('.quiz-result')).toContainText('Expected answer:')
  await page.locator('#english-toggle').click()
  await expect(page.locator('.option').first()).toBeDisabled()
  await expect(page.locator('#next-quiz')).toBeVisible()
  await page.locator('#english-toggle').click()
  await page.locator('#daily-start').click()
  await expect(page.locator('.quiz-panel')).toContainText(english.alphabet.questions[0])
  await expect(page.locator('.english-rules')).toHaveCount(0)
})

test('every lesson has readable English support at this viewport', async ({ page }, info) => {
  test.setTimeout(180000)
  await page.goto('/')
  await page.locator('#english-toggle').click()
  await page.locator('#catalogue-toggle').click()
  for (const lesson of lessons) {
    if (await page.locator('#catalogue').isHidden()) await page.locator('#catalogue-toggle').click()
    await page.locator(`[data-lesson="${lesson.id}"]`).click()
    await page.locator('#mode-grammar').click()
    await expect(page.locator('.teaching-section .english-note')).toHaveCount(lesson.sections.length)
    await expect(page.locator('.reading')).toContainText(english[lesson.id].reading)
    for (const mode of ['grammar', 'exercises', 'writing', 'speaking', 'quiz', 'cards']) {
      await page.locator(`#mode-${mode}`).click()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${lesson.id}/${mode}`).toBe(true)
    }
    await page.locator('#mode-writing').click()
    await expect(page.locator('#practice-panel')).toContainText(english[lesson.id].writing)
    if (lesson.task) await expect(page.locator('#practice-panel')).toContainText(english[lesson.id].task)
  }
  if (await page.locator('#catalogue').isVisible()) await page.locator('#catalogue-toggle').click()
  await page.screenshot({ path: info.outputPath('english-support.png'), fullPage: true })
})
