import { test, expect } from '@playwright/test'

test('lesson search, selection and section shortcuts keep practice easy to reach', async ({ page }, info) => {
  await page.goto('/')
  await page.locator('#catalogue-toggle').click()
  await page.locator('#lesson-search').fill('ecrirezz')
  await expect(page.locator('#lesson-search-status')).toContainText('Aucune')
  await page.locator('#lesson-search').fill('nombres')
  await expect(page.locator('.lesson-card:visible')).toHaveCount(1)
  await page.locator('#lesson-numbers').click()
  await expect(page.locator('#catalogue')).toBeHidden()
  await expect(page.locator('#practice-title')).toBeFocused()
  await expect(page.locator('#practice-title')).toHaveText('Les nombres')
  await page.locator('.lesson-contents a').first().click()
  await expect(page.locator('#section-0')).toBeInViewport()
  await page.locator('#english-toggle').click()
  await expect(page.locator('#mode-cards small')).toHaveText('Flashcards')
  await page.locator('#mode-cards').click()
  await expect(page.locator('.flip-hint')).toContainText('Toucher')
  await page.locator('#flashcard').click()
  await expect(page.locator('.flip-hint')).toContainText('recto')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('#practice-title').scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('improved-ui.png'), fullPage: true })
})
