import { test, expect } from '@playwright/test'
import { lessons } from '../../src/data/lessons.js'

async function choose(page, id) {
  if (await page.locator('#catalogue').isHidden()) await page.locator('#catalogue-toggle').click()
  await page.locator(`[data-lesson="${id}"]`).click()
}
async function mode(page, id) { await page.locator(`[data-mode="${id}"]`).click() }

test('practice stays above catalogue; card ratings and keyboard focus persist', async ({ page }, info) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('#catalogue')).toBeHidden()
  await expect(page.locator('.teaching-section')).toHaveCount(lessons[0].sections.length)
  await mode(page, 'cards')
  await page.locator('#next-card').click()
  await expect(page.locator('.progress-ring strong')).toHaveText('0%')
  await page.locator('#flashcard').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#flashcard')).toBeFocused()
  await expect(page.locator('#flashcard')).toHaveClass(/is-flipped/)
  await page.locator('#rate-known').click()
  await expect(page.locator('#flashcard')).toBeFocused()
  await expect(page.locator('.progress-ring strong')).not.toHaveText('0%')
  await page.reload()
  await expect(page.locator('#mode-cards')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.learning-summary')).toContainText('1 connues')
  await page.screenshot({ path: info.outputPath('practice.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('all lesson teaching, guided exercises, and quizzes work at this viewport', async ({ page }) => {
  test.setTimeout(180000)
  await page.goto('/')
  for (const lesson of lessons) {
    await choose(page, lesson.id)
    await mode(page, 'grammar')
    await expect(page.locator('.teaching-section')).toHaveCount(lesson.sections.length)
    await expect(page.locator('.reading')).toContainText(lesson.dialogue[0])
    await mode(page, 'exercises')
    for (const [i, exercise] of lesson.exercises.entries()) {
      await page.locator(`#answer-${i}`).fill(exercise.answers[0])
      await page.locator(`#check-${i}`).click()
      await expect(page.locator(`#feedback-${i}`)).toContainText('Correct !')
      await expect(page.locator(`#check-${i}`)).toBeFocused()
    }
    for (const id of ['writing', 'speaking', 'cards', 'quiz']) {
      await mode(page, id)
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
      expect(overflow, `${lesson.id}/${id}`).toBe(false)
      const clipped = await page.locator('.practice-single').evaluate(element => {
        const box = element.getBoundingClientRect()
        return [...element.querySelectorAll('button, textarea, input, h3, p')].some(child => { const r = child.getBoundingClientRect(); return r.left < box.left - 1 || r.right > box.right + 1 })
      })
      expect(clipped, `${lesson.id}/${id}: clipped`).toBe(false)
    }
    for (const [index, question] of lesson.quiz.entries()) {
      const answer = index === 0 ? question.options.find(option => option !== question.answer) : question.answer
      await page.getByRole('button', { name: answer, exact: true }).click()
      await expect(page.locator('.option.correct')).toHaveText(question.answer)
      await expect(page.locator('#next-quiz')).toBeFocused()
      await expect(page.locator('.quiz-result')).toContainText(question.explanation)
      await page.locator('#next-quiz').click()
    }
    await expect(page.locator('.quiz-complete')).toContainText('3 / 4')
    await page.locator('#restart-quiz').click()
    await expect(page.locator('.quiz-top')).toContainText('1 / 4')
  }
})

test('writing, rubric, failed exercise feedback, and category filters preserve work', async ({ page }) => {
  await page.goto('/')
  await choose(page, 'introductions')
  await mode(page, 'exercises')
  await page.locator('#answer-0').fill('wrong')
  await page.locator('#check-0').click()
  await expect(page.locator('#feedback-0')).toContainText('À retravailler')
  await page.locator('#answer-0').fill('m’')
  await expect(page.locator('#feedback-0')).toBeEmpty()
  await mode(page, 'writing')
  await page.locator('#writing-answer').fill('<b>Je suis 20 ans.</b>')
  await page.locator('#check-writing').click()
  await expect(page.locator('#writing-hints')).toContainText('j’ai … ans')
  await page.locator('#rubric-0').check()
  await page.locator('#catalogue-toggle').click()
  await page.locator('[data-category="Culture"]').click()
  await expect(page.locator('#mode-writing')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#writing-answer')).toHaveValue('<b>Je suis 20 ans.</b>')
  await expect(page.locator('.lesson-card')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('#writing-answer')).toHaveValue('<b>Je suis 20 ans.</b>')
  await page.locator('#check-writing').click()
  await expect(page.locator('#rubric-0')).toBeChecked()
  await expect(page.locator('#writing-answer b')).toHaveCount(0)
})

test('quiz answer survives reload and daily session resumes to completion', async ({ page }) => {
  await page.goto('/')
  await mode(page, 'quiz')
  await page.locator('.option').nth(1).click()
  await page.reload()
  await expect(page.locator('#next-quiz')).toBeVisible()
  await expect(page.locator('.option').first()).toBeDisabled()
  await page.locator('#daily-start').click()
  await page.locator('.option').first().click()
  await page.locator('#daily-next').click()
  await page.reload()
  await page.locator('#daily-start').click()
  await expect(page.locator('.daily-counter')).toContainText('2 / 8')
  for (let i = 1; i < 8; i++) {
    await page.locator('#flashcard').click()
    await page.locator('#rate-again').click()
  }
  await expect(page.locator('#practice-panel')).toContainText('Révision terminée')
})

test('export, validated import, cancellation and confirmed reset', async ({ page }) => {
  await page.goto('/')
  await mode(page, 'writing')
  await page.locator('#writing-answer').fill('My saved draft')
  const downloadEvent = page.waitForEvent('download')
  await page.locator('#export-progress').click()
  const download = await downloadEvent
  const path = await download.path()
  page.once('dialog', dialog => dialog.dismiss())
  await page.locator('#reset-progress').click()
  await expect(page.locator('#writing-answer')).toHaveValue('My saved draft')
  page.once('dialog', dialog => dialog.accept())
  await page.locator('#reset-progress').click()
  await mode(page, 'writing')
  await expect(page.locator('#writing-answer')).toBeEmpty()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('#import-file').setInputFiles(path)
  await expect(page.locator('#data-message')).toContainText('Sauvegarde importée')
  await expect(page.locator('#writing-answer')).toHaveValue('My saved draft')
  await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":99}') })
  await expect(page.locator('#data-message')).toContainText('Import impossible')
  await expect(page.locator('#writing-answer')).toHaveValue('My saved draft')
})

test('damaged and unavailable browser storage do not stop practice', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('af-pratique-progress', 'invalid'))
  await page.reload()
  await expect(page.locator('#practice-title')).toHaveText('Alphabet et accents')
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Unavailable') } })
  await page.reload()
  await mode(page, 'writing')
  await page.locator('#writing-answer').fill('In memory')
  await expect(page.locator('#storage-note')).toContainText('indisponible')
  await mode(page, 'cards'); await mode(page, 'writing')
  await expect(page.locator('#writing-answer')).toHaveValue('In memory')
})

test('textbook project draft persists separately and punctuation is marked accurately', async ({ page }) => {
  await page.goto('/')
  await mode(page, 'exercises')
  const index = lessons[0].exercises.findIndex(e => e.type === 'punctuation')
  await page.locator(`#answer-${index}`).fill('Tu es ici.')
  await page.locator(`#check-${index}`).click()
  await expect(page.locator(`#feedback-${index}`)).toContainText('À retravailler')
  await page.locator(`#answer-${index}`).fill('Tu es ici ?')
  await page.locator(`#check-${index}`).click()
  await expect(page.locator(`#feedback-${index}`)).toContainText('Correct !')
  await choose(page, 'messages')
  await mode(page, 'writing')
  await expect(page.locator('#practice-panel')).toContainText('Demander des idées de sortie')
  await page.locator('#writing-answer').fill('Premier exercice')
  await page.locator('#task-answer').fill('Bonjour, je voudrais le programme du dimanche.')
  await page.reload()
  await expect(page.locator('#writing-answer')).toHaveValue('Premier exercice')
  await expect(page.locator('#task-answer')).toHaveValue('Bonjour, je voudrais le programme du dimanche.')
  const downloaded = page.waitForEvent('download')
  await page.locator('#export-progress').click()
  const backup = await (await downloaded).path()
  await page.locator('#writing-answer').fill('')
  await page.locator('#task-answer').fill('')
  page.once('dialog', async dialog => {
    expect(dialog.message()).toContain('2 brouillon(s)')
    await dialog.accept()
  })
  await page.locator('#import-file').setInputFiles(backup)
  await expect(page.locator('#data-message')).toContainText('Sauvegarde importée')
  await expect(page.locator('#writing-answer')).toHaveValue('Premier exercice')
  await expect(page.locator('#task-answer')).toHaveValue('Bonjour, je voudrais le programme du dimanche.')
})
