import { test, expect } from '@playwright/test'
import { lessons } from '../../src/data/lessons.js'

async function open(page, id) {
  await page.locator('#nav-lessons').click()
  await page.locator(`#lesson-${id}`).click()
}

test('all lessons: exercises and quiz are checked one at a time', async ({ page }) => {
  test.setTimeout(240000)
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  for (const lesson of lessons) {
    await open(page, lesson.id)
    await expect(page.locator('.teaching-section')).toHaveCount(lesson.sections.length)
    await page.locator('#tab-quiz').click()
    await expect(page.locator('#step-exercises')).toHaveAttribute('aria-pressed', 'true')
    for (const [i, exercise] of lesson.exercises.entries()) {
      await expect(page.locator('.activity .meta').first()).toHaveText(`Exercice ${i + 1} / ${lesson.exercises.length} · correction automatique`)
      await page.locator('#exercise-answer').fill(exercise.answers[0])
      await page.locator('#exercise-answer').press('Enter')
      await expect(page.locator('#exercise-feedback')).toContainText('Correct !')
      const next = i === lesson.exercises.length - 1 ? '#exercises-done' : '#next-exercise'
      await expect(page.locator(next)).toBeFocused()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${lesson.id}/exercise ${i}`).toBe(true)
      await page.locator(next).click()
    }
    await expect(page.locator('#step-quiz')).toHaveAttribute('aria-pressed', 'true')
    for (const [index, question] of lesson.quiz.entries()) {
      const answer = index === 0 ? question.options.find(option => option !== question.answer) : question.answer
      await page.locator('.option').nth(question.options.indexOf(answer)).click()
      await expect(page.locator('.option.correct')).toHaveText(question.answer)
      await expect(page.locator('.option:disabled')).toHaveCount(question.options.length)
      if (index === 0) await expect(page.locator('.option.wrong')).toHaveText(answer)
      await expect(page.locator('#next-quiz')).toBeFocused()
      await expect(page.locator('.feedback')).toContainText(question.explanation)
      await page.locator('#next-quiz').click()
    }
    await expect(page.locator('#quiz-complete')).toContainText(`${lesson.quiz.length - 1} / ${lesson.quiz.length}`)
    await page.locator('#restart-quiz').click()
    await expect(page.locator('.activity .meta').first()).toContainText(`Question 1 / ${lesson.quiz.length}`)
  }
  await page.locator('#nav-today').click()
  await expect(page.locator('.stat').nth(2)).toContainText(`${lessons.at(-1).quiz.length - 1}/${lessons.at(-1).quiz.length}`)
  expect(errors).toEqual([])
})

test('wrong exercise answers can be retried and punctuation is marked accurately', async ({ page }) => {
  await page.goto('/')
  await open(page, 'alphabet')
  await page.locator('#tab-quiz').click()
  await page.locator('#exercise-answer').fill('wrong')
  await page.locator('#check-exercise').click()
  await expect(page.locator('#exercise-feedback')).toContainText('À retravailler')
  await page.locator('#exercise-answer').fill('é')
  await expect(page.locator('#exercise-feedback')).toBeEmpty()
  await expect(page.locator('#exercise-answer')).toBeFocused()
  const index = lessons[0].exercises.findIndex(e => e.type === 'punctuation')
  for (let i = 0; i < index; i++) await page.locator('#following-exercise').click()
  await page.locator('#exercise-answer').fill('Tu es ici.')
  await page.locator('#check-exercise').click()
  await expect(page.locator('#exercise-feedback')).toContainText('À retravailler')
  await page.locator('#exercise-answer').fill('Tu es ici ?')
  await page.locator('#check-exercise').click()
  await expect(page.locator('#exercise-feedback')).toContainText('Correct !')
})

test('quiz answer survives reload', async ({ page }) => {
  await page.goto('/')
  await page.locator('#continue').click()
  await page.locator('#tab-quiz').click()
  await page.locator('#step-quiz').click()
  await page.locator('.option').nth(1).click()
  await page.reload()
  await page.locator('#continue').click()
  await expect(page.locator('#next-quiz')).toBeVisible()
  await expect(page.locator('.option').first()).toBeDisabled()
})

test('writing, model answer, rubric and textbook project persist', async ({ page }, info) => {
  await page.goto('/')
  await open(page, 'messages')
  await page.locator('#tab-write').click()
  await expect(page.locator('#activity-panel')).toContainText('Demander des idées de sortie')
  await page.locator('#writing-answer').fill('<b>Premier exercice</b>')
  await page.locator('#task-answer').fill('Bonjour, je voudrais le programme du dimanche.')
  await page.locator('#toggle-model').click()
  await expect(page.locator('.model')).toContainText(lessons.find(l => l.id === 'messages').writing.model)
  await page.locator('#rubric-0').check()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('writing.png'), fullPage: true })
  await page.reload()
  await page.locator('#continue').click()
  await expect(page.locator('#writing-answer')).toHaveValue('<b>Premier exercice</b>')
  await expect(page.locator('#writing-answer b')).toHaveCount(0)
  await expect(page.locator('#task-answer')).toHaveValue('Bonjour, je voudrais le programme du dimanche.')
  await page.locator('#toggle-model').click()
  await expect(page.locator('#rubric-0')).toBeChecked()
})

test('export, validated import, cancellation and confirmed reset', async ({ page }) => {
  await page.goto('/')
  await page.locator('#continue').click()
  await page.locator('#tab-write').click()
  await page.locator('#writing-answer').fill('My saved draft')
  await page.locator('#nav-carnet').click()
  const downloadEvent = page.waitForEvent('download')
  await page.locator('#export-progress').click()
  const path = await (await downloadEvent).path()
  page.once('dialog', dialog => dialog.dismiss())
  await page.locator('#reset-progress').click()
  await expect(page.locator('#data-message')).not.toContainText('réinitialisé')
  page.once('dialog', dialog => dialog.accept())
  await page.locator('#reset-progress').click()
  await expect(page.locator('#data-message')).toContainText('réinitialisé')
  page.once('dialog', async dialog => {
    expect(dialog.message()).toContain('1 brouillon(s)')
    await dialog.accept()
  })
  await page.locator('#import-file').setInputFiles(path)
  await expect(page.locator('#data-message')).toContainText('Sauvegarde importée')
  await page.locator('#import-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":99}') })
  await expect(page.locator('#data-message')).toContainText('Import impossible')
  await page.locator('#nav-today').click()
  await page.locator('#continue').click()
  await expect(page.locator('#writing-answer')).toHaveValue('My saved draft')
})

test('damaged and unavailable browser storage do not stop practice', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('af-pratique-progress', 'invalid'))
  await page.reload()
  await expect(page.locator('.next-title')).toHaveText('Alphabet et accents')
  await page.addInitScript(() => { Storage.prototype.setItem = () => { throw new Error('Unavailable') } })
  await page.reload()
  await page.locator('#continue').click()
  await page.locator('#tab-write').click()
  await page.locator('#writing-answer').fill('In memory')
  await expect(page.locator('#storage-draft')).toContainText('indisponible')
  await page.locator('#tab-cards').click()
  await page.locator('#tab-write').click()
  await expect(page.locator('#writing-answer')).toHaveValue('In memory')
  await page.locator('#nav-carnet').click()
  await expect(page.locator('#storage-note')).toContainText('indisponible')
})
